# kustomization.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patchesStrategicMerge:
  - pod.puppet-ubuntu.yaml
  - pod.puppet-oraclelinux.yaml
