# ingress.hello-whale.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: hello-whale
  namespace: default
spec:
  rules:
  - host: hello-whale.default
    http:
      paths:
      - path: /blue/(.*)
        pathType: Prefix
        backend:
          service:
            name: hello-whale
            port:
              number: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - hello-whale.default
    secretName: hello-whale-cert