# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.devcontainer.yaml
  - configmap.git-config.yaml
  - configmap.r10k-config.yaml
  - pod.puppet-oraclelinux.yaml
  - pod.puppet-ubuntu.yaml
