# pvc.workspaces.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspaces
  namespace: devpod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # rancher-specific?
  resources:
    requests:
      storage: 2Gi